### PR TITLE
Initial Dependency Management Framework

### PR DESCRIPTION
**Pull request by ritster**

### CODE REVIEW

**Comment by ritster** [comment]
xref: https://github.com/ianholmeslab/bilby_encoder/issues/11

**Comment by cmdcolin** [comment]
this is great. can you add a section to the README that explains how to use? i think it is like 'pip install .' ?

also any thoughts on using poetry? this would make a lockfile that can make it more reproducible

**Comment by ritster** [comment]
Yup, all that should be needed now is a simple ```pip install .``` from the base directory. I can add that to the project README.md when we start to get that documentation in place.

On poetry: I think that's a question of how mature this project is eventually going to be. If this is near-complete functionality (thus not too many more dependencies), then pip should be more than good enough. If we want production-grade code with robust dependency management because we are constantly extending functionality, efficiency, etc., then we should probably switch to poetry. Poetry is a package manager + project manager, but using it simply for resolving dependencies shouldn't cause too much overhead, so I'm happy to switch if that seems like a better option to you and others.

**Comment by cmdcolin** [comment]
excellent, i'd say whatever you think, i defer to you :)

 I like lockfiles a lot in javascript but know it's a bit less common in python for whatever rason

**Pull request merged**
