### PR TITLE
Output bedgraph from tool

### PR DESCRIPTION
**Pull request by cmdcolin**
This is an add-on to https://github.com/ianholmeslab/bilby_encoder/pull/8 that converts the transition matrix into a bedgraph file with multiple score columns, which allows the values to be visualized in the genome browser

example:

image

the bedgraph format is not particularly "efficient" in memory, no "run length encoding" for example (many repeated values of the same score if there is the same score across a large range of bases) but for smallish windows of data, it works pretty ok!

kind of just an experiment but i thought it could be fun. the bedgraph or raw transition matrix could also be plotted using python tools instead of jbrowse too, but i always like to tie jbrowse into things:)

### CODE REVIEW

**Comment by ihh** [comment]
This is super cool. I would like to use this image in a proposal. Could you maybe natsort the score column labels, or (even better) give them meaningful names ("Start->Unspliced" etc)?

**Comment by cmdcolin** [comment]
yes, i'll try to get the proper names added here shortly

**Comment by cmdcolin** [comment]
@ihh here it is with the row labels corresponding to the transitions. I believe it makes sense, where the "n->n" is in the intronic skip regions, and m->m is in the coverage regions

 
Screenshot From 2024-11-19 20-14-35

you can also zoom in and see the m->n and n->m transitions

image

**Comment by cmdcolin** [comment]
here is a usable session URL with that small test run dataset loaded

https://jbrowse.org/code/jb2/bedgraph/?config=test_data%2Fconfig_demo.json&session=share-bQfN_Uha0y&password=CqdJq

**Comment by cmdcolin** [comment]
woop, fixed share link, and used "full names" (intron instead of n, match instead of m) maybe avoids aggressive cloudfront cache https://s3.amazonaws.com/jbrowse.org/code/jb2/bedgraph/index.html?config=test_data%2Fconfig_demo.json&session=share-Nh4n6sg3F4&password=Lc4Xi

image

**Comment by cmdcolin** [comment]
(also note that the source BAM plotted here is "Pair-end strand specific" Illumina reads from this sample data from rseqc https://rseqc.sourceforge.net/ see section "Download test datasets")

**Comment by ihh** [comment]
Awesome! Thanks.

**Review by ritster — APPROVED** [review]

**Pull request merged**
